---
version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4
    working_directory: ~/repo
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec ruby htmlparser.rb
workflows:
  version: 2
  normal_workflow:
    job:
      - build
  schedule_workflow:
    triggers:
      - schedule:
          cron: "00 12 * * *" # UTCで記述。-9
          filters:
            branches:
              only:
                - master
    jobs:
      - build